### PR TITLE
Expose saveSettings function

### PR DESCRIPTION
**Pull request by G-Ray**
- Added "saveSettings()" function
- Added function to the example app

### CODE REVIEW

**Review by tony-go — APPROVED** [review]
no tests?

**Comment by G-Ray** [comment]
> no tests?

Unfortunately we have no tests for `react-native-transmission` yet

**Comment by tony-go** [comment]
> > no tests?
> 
> Unfortunately we have no tests for `react-native-transmission` yet

I don't know how we could approach tests in this context tho.

**Pull request merged**
